<<<<<<< HEAD
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import type { Metadata } from 'next';
import { Poppins, Geist_Mono } from 'next/font/google';
import { StagewiseToolbar } from '@stagewise/toolbar-next';
import { ReactPlugin } from '@stagewise-plugins/react';
import './globals.css';

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'UserAuth Demo - Secure Authentication System',
  description:
    'A modern authentication system built with Next.js, featuring secure user registration, login functionality, and protected dashboard access.',
>>>>>>> 9536c36 (merge)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
=======
      <body className={`${poppins.variable} ${geistMono.variable} antialiased`}>
        <StagewiseToolbar
          config={{
            plugins: [ReactPlugin],
          }}
        />
>>>>>>> 9536c36 (merge)
        {children}
      </body>
    </html>
  );
}
