name: Jira to GitHub Bridge

on:
  schedule:
    # Check for new Jira tickets every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  sync-jira-tickets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for New Jira Tickets with ai-test Label
        id: check_jira
        env:
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }}
        run: |
          # Search for ai-test tickets created in last 10 minutes that don't have github-synced label
          JQL="labels = ai-test AND created >= -10m AND labels != github-synced ORDER BY created DESC"
          
          # Encode JQL for URL
          ENCODED_JQL=$(echo "$JQL" | jq -sRr @uri)
          
          # Get tickets from Jira
          RESPONSE=$(curl -s \
            -u "$JIRA_EMAIL:$JIRA_TOKEN" \
            -H "Accept: application/json" \
            "https://$JIRA_DOMAIN/rest/api/3/search?jql=$ENCODED_JQL&maxResults=10")
          
          echo "response=$RESPONSE" >> $GITHUB_OUTPUT
          
          # Count issues
          ISSUE_COUNT=$(echo "$RESPONSE" | jq '.issues | length')
          echo "issue_count=$ISSUE_COUNT" >> $GITHUB_OUTPUT
          
          echo "Found $ISSUE_COUNT new ai-test tickets"

      - name: Skip bridge (disabled)
        run: |
          echo "Bridge is disabled for this repo."

